NAME = libft.a

SRC = ft_bzero.c \
	ft_isalnum.c	\
	ft_isalpha.c	\
	ft_isascii.c	\
	ft_isdigit.c	\
	ft_isprint.c	\
	ft_memcpy.c	\
	ft_memmove.c	\
	ft_memset.c	\
	ft_strchr.c	\
	ft_strlcat.c	\
	ft_strlcpy.c	\
	ft_strlen.c	\
	ft_strrchr.c	\
	ft_tolower.c	\
	ft_toupper.c	\


OBJ = ??

CC = cc
FLAGS = -Wall -Werror -Wextra
RM = rm -f
HEADER = libft.h

all : $(NAME)

clean : 
	$(RM) ???

fclean : clean
	$(RM) $(NAME) ?

re : fclean all
